---
title: "CPLN505-Assignment 3"
author: "Yihong Hu"
date: "4/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(stargazer)
library(sf)
library(kableExtra)
```

# Introduction

```{r Load Data}
# Read Chester land use Data and its geometry
Chester_L <- read.csv("Chester_Urban_Growth.csv") 
Chester_L_geo <-
  Chester_L%>%
  st_as_sf(coords=c("X","Y"),crs = "EPSG:25832")

head(Chester_L)
```

## 1. Summary Statistics 

```{r Chester Summary Statistics, echo=FALSE}
#Retrieve Numeric Data
Chester_Numeric <-
  Chester_L %>%
  select_if(~any(. > 1)) %>%
  select(-X, -Y)

#Summary Statistics in the Table
summary(Chester_Numeric) %>% kable() %>% kable_styling(bootstrap_options = "striped", full_width = T, position = "left", fixed_thead = T)
```

## 2. Binary Variables

```{r Binary}
#Find urban land use change between 1992 and 2001
Chester_L <-
  Chester_L %>%
  mutate(CHNG_URB = URBAN01 - URBAN92) 

#Negative indicates that the urban land use  in 1992 has changed to other use in 2021. Replace them with 0.
Chester_L$CHNG_URB[Chester_L$CHNG_URB < 0] <- 0

```

## 3. Build Binomial Model 

```{r}
head(Chester_L)

bi_model <-
  glm(CHNG_URB ~ FOURLNE300 + INTERST800 + REGRAIL300 + RAILSTN100 + PARKS500M + WATER100 + CITBORO_10 + POPDEN90 + MEDINC90 + MEDHSEVAL_ + PCT_WHITE_ + PCT_SFHOME + PCT_POV_90 + PCT_HSB_19 + PCT_COLGRD
, family = binomial, data = Chester_L)

#Backward Selection
step( glm(CHNG_URB ~ FOURLNE300 + INTERST800 + REGRAIL300 + RAILSTN100 + PARKS500M + WATER100 + CITBORO_10 + POPDEN90 + MEDINC90 + MEDHSEVAL_ + PCT_WHITE_ + PCT_SFHOME + PCT_POV_90 + PCT_HSB_19 + PCT_COLGRD+DIST_WATER
+ DIST_RAILS + DIST_REGRA + DIST_PASSR + DIST_4LNE_ + DIST_INTER+ DIST_PARKS, family = binomial, data = Chester_L), direction="backward")

summary(bi_model)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
